### ISSUE TITLE
Camera intrinsic parameters and distortion coefficients

### ISSUE THREAD

**Issue by qijiahui7** [GAP-LAB-CUHK-SZ/Total3DUnderstanding#52]
I want to run my own captured photos using a demo. Following the steps, I input the bounding box coordinates (xmin, ymin, xmax, ymax) and label, as well as the camera intrinsic parameters and the image. However, I found that the 3D reconstruction result is not satisfactory, and the bounding boxes for objects like tables and chairs are not accurately selected. I'm not sure if it's because I didn't input the camera distortion or some other unknown reasons. I hope to get a response. Thank you.

**Comment by yinyunie** [comment]
Hi,

Since our model is trained on SUNRGBD, I am not sure if your camera intrinsics and image size are similar to the cameras in this dataset. If not, there could be a domain gap and I would recommend you to rescale your image and camera intrinsics to the same as in the dataset.
