### ISSUE TITLE
System environment problem

### ISSUE THREAD

**Issue by Ben-Aff** [GAP-LAB-CUHK-SZ/Total3DUnderstanding#55]
I can run on the Ubuntu system, but when I switched to the Windows environment, I have not been successful due to various library issues. Are you saying that Windows is not supported?
I have tried torch1.4  1.5 1.12 ,but all failed.problem in cpp_extension.py and "ninja".
Can anyone tell me how to solve it in Windows environment?

**Comment by jinzita142857** [comment]
Hello, I also had the same issue, did you solve it?

**Comment by yinyunie** [comment]
Hi,

We only tested this repository on a Linux system, because most of the dependencies are on Linux.
