### ISSUE TITLE
The pretrained model link is invalid, please update it. Thanks

### ISSUE THREAD

**Issue by FrankMMMMMM** [GAP-LAB-CUHK-SZ/Total3DUnderstanding#57]

**Comment by yinyunie** [comment]
Thanks a lot for your reminding. Will update it soon.

**Comment by yinyunie** [comment]
Hi,

I have updated the pretrained links. Please check again. Will update the preprocessed data links soon as I am considering transferring them to a new drive.

**Comment by FrankMMMMMM** [comment]
Ok. Thanks

**Comment by yinyunie** [comment]
Hi,

All links are updated. Please have a check. Thanks.
